Clean up config building
trela-official/rabbitmq-pika-flask pull request #56
Opened 2023-04-11 14:34 UTC by gverm

Support configuring from both app config and environment.

Set 'development' mode consistently and don't make it the default.

Stop relying on 'FLASK_ENV' as it is deprecated.

2023-04-17 16:46 UTC, gverm commented
I think supporting both should work. Will do change that in the coming days.

2023-04-18 11:22 UTC, gverm commented
@rafaelclp I've changed it now to check the `ENV` config key and the `FLASK_ENV` environment variable as well. Do note that this is a breaking change for people using positional arguments as the `development` parameter is removed.

2023-04-18 16:04 UTC, rafaelclp commented
@gverm Yeah, this would break for us. We actually use the `development` arg in certain situations to override the env. We could just fix it in our code, but we have way too many microservices that would need to be changed, and I worry other people using this lib could be in the same situation. In any case, I will let @aylton-almeida decide.

After we've made a decision on this I will deploy a new version.

2023-04-18 16:08 UTC, gverm commented
@rafaelclp I could just leave the parameter be so you can still keep the override, but keep the other cleanup. I'll make sure to update the documentation and examples as well then.

2023-04-18 16:13 UTC, rafaelclp commented
Thanks! That would be appreciated.

2023-04-19 08:26 UTC, gverm commented
@rafaelclp This should be OK now.

2023-04-20 00:38 UTC, rafaelclp requested changes

2023-04-20 00:38 UTC, rafaelclp commented on rabbitmq_pika_flask/RabbitMQ.py
> +        )
I don't think this works as expected.

`os.getenv` always returns a `str|None`, so if I pass `FLASK_DEBUG=0`, it will still count as a truthy value. Maybe `os.getenv("FLASK_DEBUG") == "1"`. I think `app.config.get` is similar.

Also, if I decide to override the environment variables by passing `development` in, I will only be able to override from False to True, but not vice-versa. Because if `development is False`, it will simply check the variables to find the first expression that's truthy. I believe it would be better to make `development: Optional[bool] = None` in the method args, and then do: `self.development = development if development is not None else ( check env vars here )`.

```suggestion
        self.development = development if development is not None else (
            self.config.get("ENV") == "development"
            or os.getenv("FLASK_ENV") == "development"
            or self.config.get("DEBUG") == "1"
            or os.getenv("FLASK_DEBUG") == "1"
        )
```

2023-04-20 00:39 UTC, rafaelclp commented on rabbitmq_pika_flask/RabbitMQ.py
> +        )
Just one last change request, I promise :)!

2023-04-20 20:35 UTC, gverm commented
@rafaelclp Thanks for the review and fix suggestion :) Hopefully all good now!

OT: Just in case you missed it, #57 would best be merged before a new release is done, so we don't have to break positional arguments after a release.

2023-04-24 16:35 UTC, rafaelclp commented
Thanks for the contribution. I'm merging this now, and after we merge your other PR, I will bump the version.

2023-04-24 16:35 UTC, merged

2023-04-24 21:50 UTC, gverm commented
@rafaelclp Thanks for pointing that out, I copied it from the existing code, my bad :sweat_smile: 

Thanks for merging :)